### ISSUE TITLE
React + Redux frontend 와 django 를 통한 RESTful Server 를 통한 풀스택 아키텍쳐 구현하기

### ISSUE THREAD

**Issue by shalomeir** [KoreaHTML5/webframeworks.kr#117]
React + Redux frontend 와 django 를 통한 RESTful Server 를 통한 풀스택 아키텍쳐 구현하기 에 대한 Tutorial 포스팅을 기존의 제 [블로그](http://www.shalomeir.com)의 '[snippod-starter-demo-app – Full Stack Architecture : React & Flux + Django REST Framework](http://www.shalomeir.com/2016/07/snippod-starter-demo-app-full-stack-react-redux-django/)' 포스팅을 활용하여 업로드할 예정입니다.

**Comment by jeonghwan-kim** [comment]
b3c42a20980554fe5b27b4364febf063ba57270c
