### ISSUE TITLE
기존 번역본들 업데이트입니다.

### ISSUE THREAD

**Issue by pouu69** [KoreaHTML5/webframeworks.kr#126]
새롭게 webframeworks.kr 작성자로 참가하게 된 [FEDevelopers/tech.description 번역팀](https://github.com/FEDevelopers/tech.description/wiki/%EB%B2%88%EC%97%AD-%EB%AC%B8%EC%84%9C) 박관웅입니다.  
좋은기회 주셔서 감사 인사 말씀 드립니다.  

일단 지금까지 진행 했던 번역글을 한꺼번에 올려달라고 요청해주셔서, 제가 진행한 다음 리스트를 올리려고 합니다.

- [Webpack의 혼란스런 사항들](https://github.com/FEDevelopers/tech.description/wiki/Webpack%EC%9D%98-%ED%98%BC%EB%9E%80%EC%8A%A4%EB%9F%B0-%EC%82%AC%ED%95%AD%EB%93%A4)
- [[ES6] 비동기 프로그래밍](https://github.com/FEDevelopers/tech.description/wiki/%5BES6%5D-%EB%B9%84%EB%8F%99%EA%B8%B0-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D)
- [[ES6] Promises(1): the API](https://github.com/FEDevelopers/tech.description/wiki/%5BES6%5D-Promises(1):-the-API)
- [[ES6] Promises(2): the API](https://github.com/FEDevelopers/tech.description/wiki/%5BES6%5D-Promises(2):-the-API)
- [[ES6] Promises(3): the API](https://github.com/FEDevelopers/tech.description/wiki/%5BES6%5D-Promises(3):-the-API)
- [Javascript 세미콜론(;) 가이드](https://github.com/FEDevelopers/tech.description/wiki/Javascript-%EC%84%B8%EB%AF%B8%EC%BD%9C%EB%A1%A0(;)-%EA%B0%80%EC%9D%B4%EB%93%9C)

올릴 글에 대해 이슈에 간단히 소개하여 올리면 된다고 작성법에 적혀있어서 이슈 등록 합니다.  
그리고 아직  webframeworks.kr/updated 에 카테고리 분류를 어떻게 해야할지 모르겠습니다.  
가이드 부탁드리겠습니다.

감사합니다.

**Comment by apple77y** [comment]
제가 PR해 둔 내역을 참고해서 작업하시면 될 듯합니다.
확인하시고 이 이슈는 닫으셔도 될 듯.
